"""Generate docs_wiki/GEMINI.md from docs_wiki/CLAUDE.md.

`CLAUDE.md` is the source of truth. The two files differ in one section
only, 1b, which names the canvas tooling. Run this after every edit to
`CLAUDE.md`. Never edit `GEMINI.md` by hand.

    python docs_wiki/tools/sync_agent_rules.py [--check]

`--check` reports whether `GEMINI.md` is current and writes nothing. It
exits 1 when the file is stale, which suits a pre-commit hook.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
SRC = HERE / "CLAUDE.md"
DST = HERE / "GEMINI.md"

START = "## 1b. Canvas and Excalidraw Files"
END = "## 1c."

GEMINI_1B = """## 1b. Canvas and Excalidraw Files
- A `.canvas` file is a schematic of the UI, in JSON Canvas format.
- **Never write a `.canvas` by hand.** Hand-placed nodes drift off the 20
  pixel grid and cannot be nudged without jumping.
- Keep every coordinate on the 20 pixel grid. Put group nodes first in the
  array.
- The canvas tooling lives in the `claude-canvas` plugin at
  `~/.claude/skills/canvas`, with the scripts `canvas_validate.py`,
  `canvas_layout.py`, and `canvas_template.py`. Run `canvas_validate.py` on
  every canvas you write. If you cannot run it, do not write the canvas.
- `.excalidraw` files are hand-made. Treat them as read-only.

"""

BANNER = (
    "<!-- GENERATED FROM CLAUDE.md. Do not edit this file by hand.\n"
    "     Edit docs_wiki/CLAUDE.md, then run:\n"
    "       python docs_wiki/tools/sync_agent_rules.py -->\n\n"
)


def build():
    src = SRC.read_text(encoding="utf-8")
    i, j = src.index(START), src.index(END)
    body = src[:i] + GEMINI_1B + src[j:]
    head, sep, rest = body.partition("\n")   # keep the H1 on line 1
    return head + sep + "\n" + BANNER + rest.lstrip("\n")


def main():
    want = build()
    if "--check" in sys.argv:
        have = DST.read_text(encoding="utf-8") if DST.exists() else ""
        if have == want:
            print("GEMINI.md is current")
            return 0
        print("GEMINI.md is STALE. Run: python docs_wiki/tools/sync_agent_rules.py")
        return 1
    DST.write_text(want, encoding="utf-8")
    print(f"wrote {DST.relative_to(HERE.parent)} from {SRC.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
